from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Mapping

from .json_tools import extract_json_object, write_json, write_text


@dataclass
class JsonAgent:
    """A small fixed-prompt JSON agent.

    The prompt is fixed by the framework, but the output is generated by the LLM
    on every run from the provided sandbox inputs. This is the intended EG-RSA
    bootstrap behavior: do not hard-code environment_understanding,
    target_alignment_contract, or reward_schema contents.
    """

    name: str
    llm_client: Any
    prompt_template: str

    def build_prompt(self, inputs: Mapping[str, str]) -> str:
        prompt = self.prompt_template
        for key, value in inputs.items():
            prompt = prompt.replace("{{" + key + "}}", value)
        return prompt

    def run(self, inputs: Mapping[str, str], output_path: str | Path, raw_output_path: str | Path) -> Dict[str, Any]:
        prompt = self.build_prompt(inputs)
        raw = self.llm_client.generate(prompt)
        write_text(raw_output_path, raw)
        parsed = extract_json_object(raw)
        parsed.setdefault("agent_name", self.name)
        write_json(output_path, parsed)
        return parsed
