from __future__ import annotations

import ast
import traceback
from pathlib import Path
from typing import Any, Dict, List, Type

import gymnasium as gym
import numpy as np

from .env_builder import make_single_env
from .json_tools import write_json


class _SelfMethodCallVisitor(ast.NodeVisitor):
    def __init__(self) -> None:
        self.calls: List[str] = []

    def visit_Call(self, node: ast.Call) -> Any:
        func = node.func
        if isinstance(func, ast.Attribute) and isinstance(func.value, ast.Name) and func.value.id == "self":
            self.calls.append(func.attr)
        self.generic_visit(node)


def validate_reward_runtime_safety(reward_code: str) -> Dict[str, Any]:
    """Static guard for runtime-fragile generated reward code.

    Generated reward is appended as exactly one class method. Therefore it must
    not call extra helper methods on self unless the framework explicitly created
    them. Internal state is still allowed via direct self attributes, e.g.
    if not hasattr(self, '_x'): self._x = 0.
    """
    errors: List[str] = []
    warnings: List[str] = []
    try:
        tree = ast.parse(reward_code)
    except SyntaxError as exc:
        return {"valid": False, "errors": [f"SyntaxError: {exc}"], "warnings": warnings}

    visitor = _SelfMethodCallVisitor()
    visitor.visit(tree)
    if visitor.calls:
        errors.append(
            "Reward code calls helper methods on self that are not generated by the single-function contract: "
            + ", ".join(sorted(set(visitor.calls)))
            + ". Use direct hasattr/self-attribute initialization inside compute_reward instead."
        )

    return {"valid": len(errors) == 0, "errors": errors, "warnings": warnings, "self_method_calls": sorted(set(visitor.calls))}


def smoke_test_reward_env(
    env_cls: Type[gym.Env],
    env_kwargs: Dict[str, Any],
    max_episode_steps: int | None,
    seed: int | None,
    output_path: str | Path,
    n_steps: int = 8,
) -> Dict[str, Any]:
    """Run a short reset/step check before expensive PPO training."""
    output_path = Path(output_path)
    report: Dict[str, Any] = {
        "valid": False,
        "stage": "not_started",
        "n_steps_requested": int(n_steps),
        "steps_completed": 0,
        "errors": [],
        "warnings": [],
    }
    env = None
    try:
        report["stage"] = "make_env"
        env = make_single_env(env_cls, env_kwargs, max_episode_steps, seed)
        report["stage"] = "reset"
        obs, info = env.reset(seed=seed)
        report["initial_observation_shape"] = list(np.asarray(obs).shape)
        report["stage"] = "step"
        for step_id in range(int(n_steps)):
            action = env.action_space.sample()
            obs, reward, terminated, truncated, info = env.step(action)
            float(reward)
            if not isinstance(info, dict):
                raise TypeError(f"info must be dict, got {type(info)}")
            report["steps_completed"] = step_id + 1
            if terminated or truncated:
                obs, info = env.reset(seed=None)
        report["valid"] = True
        report["stage"] = "finished"
    except Exception as exc:
        report["valid"] = False
        report["error_type"] = type(exc).__name__
        report["error_message"] = str(exc)
        report["traceback"] = traceback.format_exc(limit=12)
        report["errors"].append(f"{type(exc).__name__}: {exc}")
    finally:
        try:
            if env is not None:
                env.close()
        except Exception:
            pass
        write_json(output_path, report)
    return report
