from __future__ import annotations

import json
from pathlib import Path
from typing import Any, List

import yaml

from eg_rsa.diagnostics.attribution import RewardAttributionAnalyzer
from eg_rsa.diagnostics.hack_detectors import RewardHackDetector
from eg_rsa.memory.memory_card import MemoryCard
from eg_rsa.memory.memory_store import MemoryStore
from eg_rsa.reward.operators import RewardEditOperatorApplier
from eg_rsa.reward.safe_compiler import SafeRewardCompiler
from eg_rsa.reward.schema import RewardSchema
from eg_rsa.training.eg_rsa_trainer import EGRSATrainer


class EGRSARunner:
    """EG-RSA runner using real policy training and rollout trajectories."""

    def __init__(self, config_path: str):
        self.config_path = Path(config_path)
        if not self.config_path.exists():
            raise FileNotFoundError(f"Config not found: {self.config_path}")
        self.config = yaml.safe_load(self.config_path.read_text(encoding="utf-8"))
        self.output_dir = Path(self.config["experiment"]["output_dir"])
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def run(self) -> None:
        schema = self._load_schema(Path(self.config["eg_rsa"]["initial_schema_path"]))
        compiled_code = SafeRewardCompiler.compile(schema)
        self._write_text(self.output_dir / "compiled_reward.py", compiled_code)

        trainer = EGRSATrainer(self.config, self.output_dir)
        trajectories = trainer.train_and_record(schema)

        attribution = RewardAttributionAnalyzer.analyze(trajectories)
        detector = RewardHackDetector(**self.config.get("hack_detector", {}))
        diagnostics = detector.detect(trajectories, attribution)
        diagnostic_report = {"attribution": attribution, "diagnostics": diagnostics}
        self._write_json(self.output_dir / "diagnostic_report.json", diagnostic_report)

        memory_store = MemoryStore(self.output_dir / "memory" / "memory_cards.jsonl")
        retrieved = memory_store.retrieve(
            diagnostics.get("failure_modes", []),
            env_family=self.config.get("environment", {}).get("family", "unknown"),
            top_k=int(self.config.get("memory", {}).get("top_k", 3)),
        )
        self._write_json(self.output_dir / "retrieved_memory.json", [card.to_dict() for card in retrieved])

        edit_plan = self._fallback_edit_plan(diagnostics)
        new_schema = RewardEditOperatorApplier.apply(schema, edit_plan)
        self._write_json(self.output_dir / "reward_schema_next.json", new_schema.to_dict())
        self._write_json(self.output_dir / "edit_plan.json", {"edit_plan": edit_plan})

        memory_card = MemoryCard(
            memory_id=f"memory_{new_schema.version:04d}",
            env_family=self.config.get("environment", {}).get("family", "unknown"),
            failure_modes=diagnostics.get("failure_modes", []),
            reward_attribution=attribution,
            edit_plan=edit_plan,
            outcome={
                "note": "Outcome is measured after training reward_schema_next in the next iteration.",
                "hack_score_before": diagnostics.get("hack_score", 0.0),
            },
            lesson="Generated by real EG-RSA training diagnostics and fallback edit policy.",
            metadata={"config_path": str(self.config_path)},
        )
        memory_store.append(memory_card)
        self._write_json(self.output_dir / "latest_memory_card.json", memory_card.to_dict())

        print(f"EG-RSA real training loop finished. Outputs saved to: {self.output_dir}")

    @staticmethod
    def _fallback_edit_plan(diagnostics: dict) -> List[dict]:
        """Rule fallback before the LLM edit agent is connected.

        This is not the final research edit agent. It prevents the real training
        loop from depending on a mock edit_plan file.
        """
        target = diagnostics.get("dominant_component")
        modes = set(diagnostics.get("failure_modes", []))
        edits: List[dict] = []
        if target and "single_component_dominance" in modes:
            edits.append({"operator": "decrease_weight", "target": target, "factor": 0.5})
        if target and "repeated_event_exploitation" in modes:
            edits.append({"operator": "convert_to_one_time_event", "target": target})
        if not edits and target:
            edits.append({"operator": "clip_component", "target": target, "clip": [-1.0, 1.0]})
        return edits

    @staticmethod
    def _load_schema(path: Path) -> RewardSchema:
        with path.open("r", encoding="utf-8") as f:
            return RewardSchema.from_dict(json.load(f))

    @staticmethod
    def _write_json(path: Path, data: Any) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        with path.open("w", encoding="utf-8") as f:
            json.dump(data, f, indent=2, ensure_ascii=False)

    @staticmethod
    def _write_text(path: Path, text: str) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
